swagger: '2.0'
info:
  title: Minimal Hushfile API draft
  description: To edit this API, paste [the source](https://github.com/ysangkok/hushfile/blob/gh-pages/minimal-v1.yaml) into [the editor](http://editor.swagger.io/). When satisfied, edit the file in the source repo and make GitHub do the fork/commit/PR thing in one step.
  version: v1

host: hushfile.it

schemes:
  - https

basePath: /api
produces:
  - application/json
  - application/octet-stream
consumes:
  - application/json
paths:
  /:
    put:
      consumes:
        - multipart/form-data
      parameters:
        - name: deletekey
          in: query
          description: Key that makes it possible to delete this file. If no key is provided, the file is not deletable.
          type: string
        - name: expiry
          in: query
          description: Date-time of automatic deletion by the server. Try to parse as ISO 8601, if that doesn't work, parse as UNIX time (UTC), see Python/calendar.timegm.
          type: string
          format: date-time
      responses:
        201:
          description: Hushfile created
        400:
          description: Bad request. Schema not satisfied.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Internal server error, maybe it misconfigured.
          schema:
            $ref: '#/definitions/Error'
  /{id}:
    parameters:
      - name: id
        in: path
        description: ID of the file.
        required: true
        type: string
    head:
      description:
        Fetch length of hushfile.
      responses:
        200:
          description: The header "Content-Length" has the length in octets.
        404:
          description: ID not found.
          schema:
            $ref: '#/definitions/Error'
    get:
      description: |
        Returns the bytes of a hushfiles.
      produces:
        - application/octet-stream
      responses:
        200:
          description: Bytes of the hushfile.
        404:
          description: ID not found.
          schema:
            $ref: '#/definitions/Error'
    delete:
      description:
        Deletes a hushfile.
      responses:
        200:
          description: OK, hushfile deleted.
        403:
          description: A deletekey is needed and yours was wrong.
        404:
          description: ID not found.
          schema:
            $ref: '#/definitions/Error'
  /merge:
    post:
      description:
        Merges one or more hushfiles.
        
        The result is a hushfile which simply contains the bytes of all hushfiles, concatenated.
        
        The source hushfiles will still be available (until their eventual expiry).
      parameters:
      - name: id
        in: formData
        description: IDs of hushfiles to use
        required: true
        type: array
        minItems: 1
        items:
          type: string
        collectionFormat: csv
      responses:
        201:
          description: Hushfile created.
        400:
          description: One or more source ID's invalid.
          schema:
            $ref: '#/definitions/Error'
      
definitions:
  Error:
    type: "object"
    required: ["message"]
    properties:
      message:
        type: string
